Remove usage of deprecated functions not supported in Django 4.0
This resolves usage of deprecated functions that have been removed in Django 4.0

```
packages/django_enumfield/db/fields.py", line 8, in <module>
71
    from django.utils.encoding import force_text
72
ImportError: cannot import name 'force_text' from 'django.utils.encoding' (
```